from __future__ import annotations
from pydantic import BaseModel, Field
from datetime import date, datetime
from typing import Optional,Annotated




#IMMIGRATION
# POST /api/immigration/entry

class ImmigrationEntryRequest(BaseModel):

    passport_id: Annotated[str,
                            Field(max_length=30, description="Unique passport number")]
    
    FullName = Annotated[
    str,
    Field(max_length=100, description="Full legal name")]   

    Nationality = Annotated[
    str,
    Field(max_length=60, description="Country of citizenship")]

    Gender = Annotated[
    str,
    Field(max_length=10, description="Male / Female / Other")]
    CountryCode = Annotated[
    str,
    Field(max_length=4, description="ISO country code")]

    Occupation = Annotated[
    str,
    Field(max_length=100, description="Profession")]

    RiskLevel = Annotated[
    str,
    Field(max_length=20, description="LOW / MEDIUM / HIGH")]

    RiskReason = Annotated[
    str,
    Field(max_length=255, description="Reason generated by risk engine")]

    VisaType = Annotated[
    str,
    Field(max_length=50, description="Tourist / Business / Student")]

    ReasonToVisit = Annotated[
    str,
    Field(max_length=100, description="Purpose of visit")]

    OperatorType = Annotated[
    str,
    Field(max_length=50, description="CHECKPOST / BORDER / HOTEL / TOLL / RAIL")]

    Location = Annotated[
    str,
    Field(max_length=200, description="Readable location string")]

    Latitude = Annotated[
    float,
    Field(ge=-90, le=90)]

    Longitude = Annotated[
    float,
    Field(ge=-180, le=180)]

    PermitDays = Annotated[
    int,
    Field(ge=1, default=30)]

    DelayDays = Annotated[
    int,
    Field(ge=0)]

    PriorVisits = Annotated[
    int,
    Field(ge=0)]

    RiskScore = Annotated[
    int,
    Field(ge=0, le=200)]
